config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "jobs#index"
  resources :jobs, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :questions, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :origin_to_prefecture

  validates :job_title,               presence: true
  validates :workshop_name,           presence: true
  validates :description,             presence: true
  validates :image,                   presence: true
  validates :origin_to_prefecture_id, presence: true, numericality: { other_than: 1, message: "can't be blank" }
end

app/models/origin_to_prefecture.rb
class OriginToPrefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :jobs
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :job

  validates :name,    presence: true
  validates :title,   presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs
  has_many :questions

  with_options presence: true do
    validates :birth_date
    validates :nickname, length: { maximum: 10 }, allow_blank: true
    validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々一]+\z/, message: 'is invalid. Input full-width characters' }
    validates :last_name_kana, :first_name_kana,
              format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters' }
  end
  validates :password,
            format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'is invalid. Include both letters and numbers' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_parmitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_parmitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_date])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = Job.all.order('created_at DESC')
  end

  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
    if current_user.id != @job.user_id
      redirect_to root_path
    end
  end

  def update
    if @job.update(job_params)
      redirect_to job_path(@job)
    else
      render :edit
    end
  end

  def destroy
    if current_user.id == @job.user_id
      @job.destroy
      redirect_to root_path
    else
      redirect_to action: :index
    end
  end

  private

  def job_params
    params.require(:job).permit(:job_title, :workshop_name, :description, :origin_to_prefecture_id, :image).merge(user_id: current_user.id)
  end
  
  def set_job
    @job = Job.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to job_path(@question.job)
    else
    end
  end

  private
  def question_params
    params.require(:question).permit(:name, :title, :content).merge(user_id: current_user.id, job_id: params[:job_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/jobs/edit.html.erb
<div class="jobs-post-contents">
  <header class="jobs-post-header">
    <%= link_to image_tag("facebook_cover_photo_1.png", class:"craftlink-icon", size:'200x80'), "/"%>
  </header>
    <div class="jobs-post-main">
      <h2 class="jobs-post-title">仕事情報を入力</h2>
  <%= form_with model: @job, local: true do |f| %>

      <%= render 'shared/error_messages', model: f.object %>

      <%# 画像 %>
      <div class="img-upload">
        <div class="weight-bold-text">
          関連画像
          <span class="indispensable">必須</span>
        </div>
        <div class="click-upload">
          <p>
            クリックしてファイルをアップロード
          </p>
          <%= f.file_field :image, id:"item-image" %>
        </div>
      </div>
      <%# /画像 %>
      
      <%# 仕事情報 %>
      <div class="new-jobs">
        <div class="weight-bold-text">
          職種名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :job_title, class:"jobs-text", id:"job-title", placeholder:"職種名（必須 20文字まで)", maxlength:"20" %>
        <div class="weight-bold-text">
          店名 / 工房名
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :workshop_name, class:"jobs-text", id:"workshop_name", placeholder:"職種名（必須 20文字まで)", maxlength:"20" %>
        <div class="weight-bold-text">
          場所
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:origin_to_prefecture_id, OriginToPrefecture.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
        <div class="weight-bold-text">
          仕事内容
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :description, class:"jobs-text", id:"job-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
      </div>
      <%# /仕事情報 %>

      <%# 下部ボタン %>
      <div class="post-btn-contents">
        <%= f.submit "変更する" ,class:"post-btn" %>
        <%=link_to 'もどる', job_path, class:"back-btn" %>
      </div>
      <%# /下部ボタン %>
    </div>
  <% end %>

</div>

app/views/jobs/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <%# 画面上部の帯部分 %>
	<div class='hero'></div>
  <%# /画面上部の帯部分  %>
  <div class="container pt-5">
    <div class="mt4rem text-center mb-5 pb-4">
      <h2 class="sv-logo">職種一覧</h2>
      <p>仕事の達人たちの世界を覗いてみよう</p>
      <div class="line"></div>
    </div>
    <div class="row">
      <% @jobs.each do |job| %>
        <div class="col-md-4 mb-5">
          <div class="card shadow">
            <%= image_tag job.image, class: "job-img" %>
            <div class="card-body row align-items-end">
              <div class="col-sm-9 job_title">
                <%= job.job_title %>
                <div class="workshop_name">
                  <%= job.workshop_name %>
                </div>
              </div>
              <div class="col-sm-3 text-right">
                <%= link_to job_path(job) do%>
                  <button type="button" class="btn btn-outline-danger">
                    詳細
                  </button>
                <% end %>
					    </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= render "shared/footer" %>

app/views/jobs/new.html.erb
<div class="jobs-post-contents">
  <header class="jobs-post-header">
    <%= link_to image_tag("facebook_cover_photo_1.png", class:"craftlink-icon", size:'200x80'), "/"%>
  </header>
  <div class="jobs-post-main">
    <h2 class="jobs-post-title">仕事情報を入力</h2>
  <%= form_with model: @job, local: true do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <%# 画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        関連画像
        <span class="indispensable">必須</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /画像 %>
    
    <%# 仕事情報 %>
    <div class="new-jobs">
      <div class="weight-bold-text">
        職種名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :job_title, class:"jobs-text", id:"job-title", placeholder:"職種名（必須 20文字まで)", maxlength:"20" %>
      <div class="weight-bold-text">
        店名 / 工房名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :workshop_name, class:"jobs-text", id:"workshop_name", placeholder:"職種名（必須 20文字まで)", maxlength:"20" %>
      <div class="weight-bold-text">
        場所
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:origin_to_prefecture_id, OriginToPrefecture.all, :id, :name, {}, {class:"select-box", id:"item-category"}) %>
      <div class="weight-bold-text">
        仕事内容
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :description, class:"jobs-text", id:"job-info", placeholder:"商品の説明（必須 1,000文字まで）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。" ,rows:"7" ,maxlength:"1000" %>
    </div>
    <%# /仕事情報 %>

    <%# 下部ボタン %>
    <div class="post-btn-contents">
      <%= f.submit "投稿する" ,class:"post-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

</div>

app/views/jobs/show.html.erb
<div class="jobs-post-contents">
  <header class="jobs-post-header">
    <%= link_to image_tag("facebook_cover_photo_1.png", class:"craftlink-icon", size:'200x80'), "/"%>
  </header>
  
    <div class="jobs-post-main">
      <%= image_tag @job.image %>
      <h1><%= @job.job_title %></h1>
      <h1><%= @job.workshop_name %></h1>
      <p><%= @job.description %></P>
      <p><%= @job.origin_to_prefecture.name %></P>
    </div>

  <% if user_signed_in? %>
    <% if current_user.id == @job.user_id %>
      <%= link_to "記事の編集", edit_job_path, method: :get, class: "job-detail-btn"%>
      <P class="or-text">または</P>
      <%= link_to "削除", job_path, method: :delete, class: "job-destroy" %>
    <% else %>
      <button type="submit" class="question-btn">
        <%= image_tag "comment.png" ,class:"question-flag-icon" ,width:"20",height:"25"%>
        <%= link_to "質問する", new_job_question_path(@job), class: "job-question-btn" %>
      </button>
    <% end %>
  <% end %>

  <div class=" text-center jobs-post-main">
    <h2 class="sv-logo">質問一覧</h2>
    <div class="line"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>craftlink</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>

</html>

app/views/questions/new.html.erb
<h1>新規投稿ページ</h1>

<%= form_with model: @job, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit '投稿する' %>
<% end %>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="text-center py-5">
	<div class="mb-4">
		<i class="fa-brands fa-square-facebook fa-4x"></i>
		<i class="fa-brands fa-square-twitter fa-4x mx-5"></i>
		<i class="fa-brands fa-square-youtube fa-4x"></i>
	</div>
	<ul class="mt-3 p-0">
		<li><a href="#">ホーム</a></li>
		<li><a href="#" class="mx-3">サービス概要</a></li>
		<li><a href="#">サービス一覧</a></li>
		<li><a href="#" class="ml-3">お問合せください</a></li>
	</ul>
	<ul class="small mb-5 p-0">
		<li>サービス1</li>
		<li>サービス2</li>
	</ul>
	<p class="mb-0">©︎ 2023 Bootstrap test</p>
</footer>
  

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<header class="container fixed-top">
	<div class="bland-logo">
		<%= link_to image_tag("facebook_cover_photo_1.png", class:"craftlink-icon", size:'200x80'), "/"%>
	</div>
	<div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to '投稿する', new_job_path, class: "post-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to (current_user.nickname.present? ? current_user.nickname : current_user.first_name + "さん"), "#", class: "user-nickname" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>  
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>